services:
  db:
    image: postgres:latest
    container_name: flight_booking_database_container
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: FlightBooking
    ports:
      - "5432:5432"
    volumes:
      - ./db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
      
